# Generated by Django 3.0.7 on 2020-07-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=30)),
                ('supervisor_ph', models.CharField(max_length=30, null=True)),
                ('supervisor_email', models.EmailField(max_length=50, null=True)),
                ('group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seminar1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('thesis_title', models.CharField(max_length=100)),
                ('student_roll', models.CharField(max_length=30)),
                ('student_ph', models.CharField(max_length=30, null=True)),
                ('student_email', models.EmailField(max_length=50, null=True)),
                ('result', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.Supervisor')),
            ],
        ),
    ]
